name: pydna_test_environment
channels:
- conda-forge
- defaults
- BjornFJohansson

dependencies:

- appdirs
- biopython=1.80
- prettytable
- networkx

- pyparsing
- CAI
- requests
- numpy
- scipy
- matplotlib

- pytest
- pytest-cov
- pytest-mock
- pytest-doctestplus
- coverage
- nbval
- requests-mock

- setuptools
