name: Conda Package Build
on:
  release:
    types: [published]
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.11", "3.10", "3.9", "3.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ‚¨áÔ∏è Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: üå∞ Cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: üåç Install conda environment from pydna_build_environment with miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: pydna_build_environment
          python-version: ${{ matrix.python-version }}
          environment-file: pydna_build_environment.yml
          auto-activate-base: false
      - name: mamba info --all
        shell: bash -l {0}
        run: mamba info --all
      - name: mamba config
        shell: bash -l {0}
        run: conda config --set anaconda_upload yes
      - name: üî© Build conda package with mamba
        shell: bash -l {0}
        run: mamba build --python ${{ matrix.python-version }} --no-include-recipe --dirty --token ${{ secrets.ANACONDATOKEN }} .
