name: Conda Build
on:
  release:
    types: [published]
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.9", "3.8", "3.7", "3.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 0
      - name: Cache conda
        uses: actions/cache@v2.1.1
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('environment-ci.yml') }}
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.7.0
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: pydna_build_environment
          python-version: ${{ matrix.python-version }}
          environment-file: pydna_build_environment.yml
      - name: conda info
        shell: bash -l {0}
        run: conda info --all
      - name: conda config
        shell: bash -l {0}
        run: conda config --set anaconda_upload yes
      - name: Build conda package
        shell: bash -l {0}
        run: conda build --python ${{ matrix.python-version }} --no-include-recipe --dirty --token ${{ secrets.ANACONDATOKEN }} .
